// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }
//bad key: AIzaSyAu_HffCDir26M7i7Oh6rWDaro-HXmVbaY
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcAXlT6hoou41oEgIbjRTCagAJzBTsZIM',
    appId: '1:854189510560:web:4e6e9f73ae347af536dec5',
    messagingSenderId: '854189510560',
    projectId: 'kasie-transie-3',
    authDomain: 'kasie-transie-3.firebaseapp.com',
    storageBucket: 'kasie-transie-3.appspot.com',
    measurementId: 'G-BQW5ZWEKB4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3finIgPi481q3-GaEDjOLcoPbs664gTs',
    appId: '1:854189510560:android:e32b4e800f7ea0e036dec5',
    messagingSenderId: '854189510560',
    projectId: 'kasie-transie-3',
    storageBucket: 'kasie-transie-3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBCW2jYebHUN609zOFxgTnm0JWP-1Y40s',
    appId: '1:854189510560:ios:a9ffeac3b25f452836dec5',
    messagingSenderId: '854189510560',
    projectId: 'kasie-transie-3',
    storageBucket: 'kasie-transie-3.appspot.com',
    iosClientId: '854189510560-5gs4ds1u1e4ej73m3ss1uack8hsegkcd.apps.googleusercontent.com',
    iosBundleId: 'com.boha.routes2024',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBCW2jYebHUN609zOFxgTnm0JWP-1Y40s',
    appId: '1:854189510560:ios:a9968a2684e9ca1a36dec5',
    messagingSenderId: '854189510560',
    projectId: 'kasie-transie-3',
    storageBucket: 'kasie-transie-3.appspot.com',
    iosClientId: '854189510560-jcfgioe7t1ei9ma7mspoeem3s8eld68a.apps.googleusercontent.com',
    iosBundleId: 'com.boha.routes2024.RunnerTests',
  );
}
